server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ShopService
  cloud:
    nacos:
      server-addr: localhost:8848
#      discovery:
#        cluster-name: sz
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka/
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: cn.itcast.user.pojo

logging:
  level:
    com.example: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS